
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const ContractStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  FINISHED: 'FINISHED',
  CANCELED: 'CANCELED'
} as const

export type ContractStatus = (typeof ContractStatus)[keyof typeof ContractStatus]
